class Surah {
  final int number;
  final String name;
  final String nameArabic;
  final String englishName;
  final String englishNameTranslation;
  final String revelationType;
  final int numberOfAyahs;
  final int startPage;
  final int endPage;

  const Surah({
    required this.number,
    required this.name,
    required this.nameArabic,
    required this.englishName,
    required this.englishNameTranslation,
    required this.revelationType,
    required this.numberOfAyahs,
    required this.startPage,
    required this.endPage,
  });

  factory Surah.fromJson(Map<String, dynamic> json) {
    return Surah(
      number: json['number'],
      name: json['name'],
      nameArabic: json['nameArabic'],
      englishName: json['englishName'],
      englishNameTranslation: json['englishNameTranslation'],
      revelationType: json['revelationType'],
      numberOfAyahs: json['numberOfAyahs'],
      startPage: json['startPage'],
      endPage: json['endPage'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'number': number,
      'name': name,
      'nameArabic': nameArabic,
      'englishName': englishName,
      'englishNameTranslation': englishNameTranslation,
      'revelationType': revelationType,
      'numberOfAyahs': numberOfAyahs,
      'startPage': startPage,
      'endPage': endPage,
    };
  }

  // Helper method to get display name based on language
  String getDisplayName(String languageCode) {
    return languageCode == 'ar' ? nameArabic : englishName;
  }

  // Complete list of all 114 Surahs with corrected page numbers (+1 offset applied)
  static const List<Surah> allSurahs = [
    Surah(number: 1, name: 'Al-Fatiha', nameArabic: 'الفاتحة', englishName: 'The Opening', englishNameTranslation: 'The Opening', revelationType: 'Meccan', numberOfAyahs: 7, startPage: 2, endPage: 2),
    Surah(number: 2, name: 'Al-Baqarah', nameArabic: 'البقرة', englishName: 'The Cow', englishNameTranslation: 'The Cow', revelationType: 'Medinan', numberOfAyahs: 286, startPage: 3, endPage: 50),
    Surah(number: 3, name: 'Ali \'Imran', nameArabic: 'آل عمران', englishName: 'Family of Imran', englishNameTranslation: 'The Family of Imran', revelationType: 'Medinan', numberOfAyahs: 200, startPage: 51, endPage: 77),
    Surah(number: 4, name: 'An-Nisa', nameArabic: 'النساء', englishName: 'The Women', englishNameTranslation: 'The Women', revelationType: 'Medinan', numberOfAyahs: 176, startPage: 78, endPage: 107),
    Surah(number: 5, name: 'Al-Ma\'idah', nameArabic: 'المائدة', englishName: 'The Table Spread', englishNameTranslation: 'The Table', revelationType: 'Medinan', numberOfAyahs: 120, startPage: 107, endPage: 128),
    Surah(number: 6, name: 'Al-An\'am', nameArabic: 'الأنعام', englishName: 'The Cattle', englishNameTranslation: 'The Cattle', revelationType: 'Meccan', numberOfAyahs: 165, startPage: 129, endPage: 151),
    Surah(number: 7, name: 'Al-A\'raf', nameArabic: 'الأعراف', englishName: 'The Heights', englishNameTranslation: 'The Heights', revelationType: 'Meccan', numberOfAyahs: 206, startPage: 152, endPage: 176),
    Surah(number: 8, name: 'Al-Anfal', nameArabic: 'الأنفال', englishName: 'The Spoils of War', englishNameTranslation: 'The Spoils of War', revelationType: 'Medinan', numberOfAyahs: 75, startPage: 177, endPage: 187),
    Surah(number: 9, name: 'At-Tawbah', nameArabic: 'التوبة', englishName: 'The Repentance', englishNameTranslation: 'The Repentance', revelationType: 'Medinan', numberOfAyahs: 129, startPage: 188, endPage: 207),
    Surah(number: 10, name: 'Yunus', nameArabic: 'يونس', englishName: 'Jonah', englishNameTranslation: 'Jonah', revelationType: 'Meccan', numberOfAyahs: 109, startPage: 209, endPage: 221),
    Surah(number: 11, name: 'Hud', nameArabic: 'هود', englishName: 'Hud', englishNameTranslation: 'Hud', revelationType: 'Meccan', numberOfAyahs: 123, startPage: 222, endPage: 235),
    Surah(number: 12, name: 'Yusuf', nameArabic: 'يوسف', englishName: 'Joseph', englishNameTranslation: 'Joseph', revelationType: 'Meccan', numberOfAyahs: 111, startPage: 236, endPage: 249),
    Surah(number: 13, name: 'Ar-Ra\'d', nameArabic: 'الرعد', englishName: 'The Thunder', englishNameTranslation: 'The Thunder', revelationType: 'Medinan', numberOfAyahs: 43, startPage: 250, endPage: 255),
    Surah(number: 14, name: 'Ibrahim', nameArabic: 'إبراهيم', englishName: 'Abraham', englishNameTranslation: 'Abraham', revelationType: 'Meccan', numberOfAyahs: 52, startPage: 256, endPage: 261),
    Surah(number: 15, name: 'Al-Hijr', nameArabic: 'الحجر', englishName: 'The Rocky Tract', englishNameTranslation: 'The Rocky Tract', revelationType: 'Meccan', numberOfAyahs: 99, startPage: 263, endPage: 267),
    Surah(number: 16, name: 'An-Nahl', nameArabic: 'النحل', englishName: 'The Bee', englishNameTranslation: 'The Bee', revelationType: 'Meccan', numberOfAyahs: 128, startPage: 268, endPage: 281),
    Surah(number: 17, name: 'Al-Isra', nameArabic: 'الإسراء', englishName: 'The Night Journey', englishNameTranslation: 'The Night Journey', revelationType: 'Meccan', numberOfAyahs: 111, startPage: 282, endPage: 293),
    Surah(number: 18, name: 'Al-Kahf', nameArabic: 'الكهف', englishName: 'The Cave', englishNameTranslation: 'The Cave', revelationType: 'Meccan', numberOfAyahs: 110, startPage: 294, endPage: 305),
    Surah(number: 19, name: 'Maryam', nameArabic: 'مريم', englishName: 'Mary', englishNameTranslation: 'Mary', revelationType: 'Meccan', numberOfAyahs: 98, startPage: 306, endPage: 312),
    Surah(number: 20, name: 'Ta-Ha', nameArabic: 'طه', englishName: 'Ta-Ha', englishNameTranslation: 'Ta-Ha', revelationType: 'Meccan', numberOfAyahs: 135, startPage: 313, endPage: 322),
    Surah(number: 21, name: 'Al-Anbiya', nameArabic: 'الأنبياء', englishName: 'The Prophets', englishNameTranslation: 'The Prophets', revelationType: 'Meccan', numberOfAyahs: 112, startPage: 323, endPage: 332),
    Surah(number: 22, name: 'Al-Hajj', nameArabic: 'الحج', englishName: 'The Pilgrimage', englishNameTranslation: 'The Pilgrimage', revelationType: 'Medinan', numberOfAyahs: 78, startPage: 333, endPage: 341),
    Surah(number: 23, name: 'Al-Mu\'minun', nameArabic: 'المؤمنون', englishName: 'The Believers', englishNameTranslation: 'The Believers', revelationType: 'Meccan', numberOfAyahs: 118, startPage: 342, endPage: 350),
    Surah(number: 24, name: 'An-Nur', nameArabic: 'النور', englishName: 'The Light', englishNameTranslation: 'The Light', revelationType: 'Medinan', numberOfAyahs: 64, startPage: 351, endPage: 359),
    Surah(number: 25, name: 'Al-Furqan', nameArabic: 'الفرقان', englishName: 'The Criterion', englishNameTranslation: 'The Criterion', revelationType: 'Meccan', numberOfAyahs: 77, startPage: 360, endPage: 367),
    Surah(number: 26, name: 'Ash-Shu\'ara', nameArabic: 'الشعراء', englishName: 'The Poets', englishNameTranslation: 'The Poets', revelationType: 'Meccan', numberOfAyahs: 227, startPage: 368, endPage: 377),
    Surah(number: 27, name: 'An-Naml', nameArabic: 'النمل', englishName: 'The Ant', englishNameTranslation: 'The Ant', revelationType: 'Meccan', numberOfAyahs: 93, startPage: 378, endPage: 385),
    Surah(number: 28, name: 'Al-Qasas', nameArabic: 'القصص', englishName: 'The Stories', englishNameTranslation: 'The Stories', revelationType: 'Meccan', numberOfAyahs: 88, startPage: 386, endPage: 396),
    Surah(number: 29, name: 'Al-\'Ankabut', nameArabic: 'العنكبوت', englishName: 'The Spider', englishNameTranslation: 'The Spider', revelationType: 'Meccan', numberOfAyahs: 69, startPage: 397, endPage: 404),
    Surah(number: 30, name: 'Ar-Rum', nameArabic: 'الروم', englishName: 'The Romans', englishNameTranslation: 'The Romans', revelationType: 'Meccan', numberOfAyahs: 60, startPage: 405, endPage: 411),
    Surah(number: 31, name: 'Luqman', nameArabic: 'لقمان', englishName: 'Luqman', englishNameTranslation: 'Luqman', revelationType: 'Meccan', numberOfAyahs: 34, startPage: 412, endPage: 415),
    Surah(number: 32, name: 'As-Sajdah', nameArabic: 'السجدة', englishName: 'The Prostration', englishNameTranslation: 'The Prostration', revelationType: 'Meccan', numberOfAyahs: 30, startPage: 416, endPage: 418),
    Surah(number: 33, name: 'Al-Ahzab', nameArabic: 'الأحزاب', englishName: 'The Clans', englishNameTranslation: 'The Clans', revelationType: 'Medinan', numberOfAyahs: 73, startPage: 419, endPage: 427),
    Surah(number: 34, name: 'Saba', nameArabic: 'سبأ', englishName: 'Sheba', englishNameTranslation: 'Sheba', revelationType: 'Meccan', numberOfAyahs: 54, startPage: 428, endPage: 434),
    Surah(number: 35, name: 'Fatir', nameArabic: 'فاطر', englishName: 'Originator', englishNameTranslation: 'The Originator', revelationType: 'Meccan', numberOfAyahs: 45, startPage: 435, endPage: 440),
    Surah(number: 36, name: 'Ya-Sin', nameArabic: 'يس', englishName: 'Ya-Sin', englishNameTranslation: 'Ya-Sin', revelationType: 'Meccan', numberOfAyahs: 83, startPage: 441, endPage: 446),
    Surah(number: 37, name: 'As-Saffat', nameArabic: 'الصافات', englishName: 'Those who set the Ranks', englishNameTranslation: 'Those Ranged in Ranks', revelationType: 'Meccan', numberOfAyahs: 182, startPage: 447, endPage: 453),
    Surah(number: 38, name: 'Sad', nameArabic: 'ص', englishName: 'The Letter Sad', englishNameTranslation: 'The Letter Sad', revelationType: 'Meccan', numberOfAyahs: 88, startPage: 454, endPage: 459),
    Surah(number: 39, name: 'Az-Zumar', nameArabic: 'الزمر', englishName: 'The Troops', englishNameTranslation: 'The Groups', revelationType: 'Meccan', numberOfAyahs: 75, startPage: 460, endPage: 467),
    Surah(number: 40, name: 'Ghafir', nameArabic: 'غافر', englishName: 'The Forgiver', englishNameTranslation: 'The Forgiver', revelationType: 'Meccan', numberOfAyahs: 85, startPage: 468, endPage: 476),
    Surah(number: 41, name: 'Fussilat', nameArabic: 'فصلت', englishName: 'Explained in Detail', englishNameTranslation: 'Explained in Detail', revelationType: 'Meccan', numberOfAyahs: 54, startPage: 477, endPage: 481),
    Surah(number: 42, name: 'Ash-Shura', nameArabic: 'الشورى', englishName: 'The Consultation', englishNameTranslation: 'The Consultation', revelationType: 'Meccan', numberOfAyahs: 53, startPage: 482, endPage: 489),
    Surah(number: 43, name: 'Az-Zukhruf', nameArabic: 'الزخرف', englishName: 'The Ornaments of Gold', englishNameTranslation: 'The Gold Adornment', revelationType: 'Meccan', numberOfAyahs: 89, startPage: 490, endPage: 496),
    Surah(number: 44, name: 'Ad-Dukhan', nameArabic: 'الدخان', englishName: 'The Smoke', englishNameTranslation: 'The Smoke', revelationType: 'Meccan', numberOfAyahs: 59, startPage: 497, endPage: 499),
    Surah(number: 45, name: 'Al-Jathiyah', nameArabic: 'الجاثية', englishName: 'The Crouching', englishNameTranslation: 'The Kneeling', revelationType: 'Meccan', numberOfAyahs: 37, startPage: 500, endPage: 502),
    Surah(number: 46, name: 'Al-Ahqaf', nameArabic: 'الأحقاف', englishName: 'The Wind-Curved Sandhills', englishNameTranslation: 'The Curved Sand-Hills', revelationType: 'Meccan', numberOfAyahs: 35, startPage: 503, endPage: 505),
    Surah(number: 47, name: 'Muhammad', nameArabic: 'محمد', englishName: 'Muhammad', englishNameTranslation: 'Muhammad', revelationType: 'Medinan', numberOfAyahs: 38, startPage: 506, endPage: 508),
    Surah(number: 48, name: 'Al-Fath', nameArabic: 'الفتح', englishName: 'The Victory', englishNameTranslation: 'The Victory', revelationType: 'Medinan', numberOfAyahs: 29, startPage: 511, endPage: 513),
    Surah(number: 49, name: 'Al-Hujurat', nameArabic: 'الحجرات', englishName: 'The Rooms', englishNameTranslation: 'The Dwellings', revelationType: 'Medinan', numberOfAyahs: 18, startPage: 515, endPage: 516),
    Surah(number: 50, name: 'Qaf', nameArabic: 'ق', englishName: 'The Letter Qaf', englishNameTranslation: 'The Letter Qaf', revelationType: 'Meccan', numberOfAyahs: 45, startPage: 519, endPage: 521),
    Surah(number: 51, name: 'Adh-Dhariyat', nameArabic: 'الذاريات', englishName: 'The Winnowing Winds', englishNameTranslation: 'The Wind that Scatter', revelationType: 'Meccan', numberOfAyahs: 60, startPage: 521, endPage: 523),
    Surah(number: 52, name: 'At-Tur', nameArabic: 'الطور', englishName: 'The Mount', englishNameTranslation: 'The Mount', revelationType: 'Meccan', numberOfAyahs: 49, startPage: 523, endPage: 525),
    Surah(number: 53, name: 'An-Najm', nameArabic: 'النجم', englishName: 'The Star', englishNameTranslation: 'The Star', revelationType: 'Meccan', numberOfAyahs: 62, startPage: 526, endPage: 528),
    Surah(number: 54, name: 'Al-Qamar', nameArabic: 'القمر', englishName: 'The Moon', englishNameTranslation: 'The Moon', revelationType: 'Meccan', numberOfAyahs: 55, startPage: 528, endPage: 531),
    Surah(number: 55, name: 'Ar-Rahman', nameArabic: 'الرحمن', englishName: 'The Beneficent', englishNameTranslation: 'The Most Gracious', revelationType: 'Meccan', numberOfAyahs: 78, startPage: 532, endPage: 534),
    Surah(number: 56, name: 'Al-Waqi\'ah', nameArabic: 'الواقعة', englishName: 'The Inevitable', englishNameTranslation: 'The Event', revelationType: 'Meccan', numberOfAyahs: 96, startPage: 535, endPage: 537),
    Surah(number: 57, name: 'Al-Hadid', nameArabic: 'الحديد', englishName: 'The Iron', englishNameTranslation: 'The Iron', revelationType: 'Medinan', numberOfAyahs: 29, startPage: 538, endPage: 541),
    Surah(number: 58, name: 'Al-Mujadila', nameArabic: 'المجادلة', englishName: 'The Pleading Woman', englishNameTranslation: 'She That Disputes', revelationType: 'Medinan', numberOfAyahs: 22, startPage: 542, endPage: 545),
    Surah(number: 59, name: 'Al-Hashr', nameArabic: 'الحشر', englishName: 'The Exile', englishNameTranslation: 'The Gathering', revelationType: 'Medinan', numberOfAyahs: 24, startPage: 546, endPage: 549),
    Surah(number: 60, name: 'Al-Mumtahanah', nameArabic: 'الممتحنة', englishName: 'She that is to be examined', englishNameTranslation: 'The Examined One', revelationType: 'Medinan', numberOfAyahs: 13, startPage: 550, endPage: 551),
    Surah(number: 61, name: 'As-Saff', nameArabic: 'الصف', englishName: 'The Ranks', englishNameTranslation: 'The Row', revelationType: 'Medinan', numberOfAyahs: 14, startPage: 552, endPage: 553),
    Surah(number: 62, name: 'Al-Jumu\'ah', nameArabic: 'الجمعة', englishName: 'The Congregation', englishNameTranslation: 'Friday', revelationType: 'Medinan', numberOfAyahs: 11, startPage: 554, endPage: 555),
    Surah(number: 63, name: 'Al-Munafiqun', nameArabic: 'المنافقون', englishName: 'The Hypocrites', englishNameTranslation: 'The Hypocrites', revelationType: 'Medinan', numberOfAyahs: 11, startPage: 556, endPage: 557),
    Surah(number: 64, name: 'At-Taghabun', nameArabic: 'التغابن', englishName: 'The Mutual Disillusion', englishNameTranslation: 'The Mutual Loss and Gain', revelationType: 'Medinan', numberOfAyahs: 18, startPage: 558, endPage: 559),
    Surah(number: 65, name: 'At-Talaq', nameArabic: 'الطلاق', englishName: 'The Divorce', englishNameTranslation: 'The Divorce', revelationType: 'Medinan', numberOfAyahs: 12, startPage: 560, endPage: 562),
    Surah(number: 66, name: 'At-Tahrim', nameArabic: 'التحريم', englishName: 'The Prohibition', englishNameTranslation: 'The Prohibition', revelationType: 'Medinan', numberOfAyahs: 12, startPage: 562, endPage: 563),
    Surah(number: 67, name: 'Al-Mulk', nameArabic: 'الملك', englishName: 'The Sovereignty', englishNameTranslation: 'The Kingdom', revelationType: 'Meccan', numberOfAyahs: 30, startPage: 564, endPage: 566),
    Surah(number: 68, name: 'Al-Qalam', nameArabic: 'القلم', englishName: 'The Pen', englishNameTranslation: 'The Pen', revelationType: 'Meccan', numberOfAyahs: 52, startPage: 565, endPage: 568),
    Surah(number: 69, name: 'Al-Haqqah', nameArabic: 'الحاقة', englishName: 'The Reality', englishNameTranslation: 'The Inevitable Reality', revelationType: 'Meccan', numberOfAyahs: 52, startPage: 567, endPage: 569),
    Surah(number: 70, name: 'Al-Ma\'arij', nameArabic: 'المعارج', englishName: 'The Ascending Stairways', englishNameTranslation: 'The Ways of Ascent', revelationType: 'Meccan', numberOfAyahs: 44, startPage: 568, endPage: 570),
    Surah(number: 71, name: 'Nuh', nameArabic: 'نوح', englishName: 'Noah', englishNameTranslation: 'Noah', revelationType: 'Meccan', numberOfAyahs: 28, startPage: 571, endPage: 573),
    Surah(number: 72, name: 'Al-Jinn', nameArabic: 'الجن', englishName: 'The Jinn', englishNameTranslation: 'The Jinn', revelationType: 'Meccan', numberOfAyahs: 28, startPage: 572, endPage: 574),
    Surah(number: 73, name: 'Al-Muzzammil', nameArabic: 'المزمل', englishName: 'The Enshrouded One', englishNameTranslation: 'The Wrapped in Garments', revelationType: 'Meccan', numberOfAyahs: 20, startPage: 575, endPage: 576),
    Surah(number: 74, name: 'Al-Muddaththir', nameArabic: 'المدثر', englishName: 'The Cloaked One', englishNameTranslation: 'The One Covering Himself', revelationType: 'Meccan', numberOfAyahs: 56, startPage: 575, endPage: 578),
    Surah(number: 75, name: 'Al-Qiyamah', nameArabic: 'القيامة', englishName: 'The Resurrection', englishNameTranslation: 'The Day of Resurrection', revelationType: 'Meccan', numberOfAyahs: 40, startPage: 577, endPage: 578),
    Surah(number: 76, name: 'Al-Insan', nameArabic: 'الإنسان', englishName: 'The Man', englishNameTranslation: 'Man', revelationType: 'Medinan', numberOfAyahs: 31, startPage: 579, endPage: 581),
    Surah(number: 77, name: 'Al-Mursalat', nameArabic: 'المرسلات', englishName: 'The Emissaries', englishNameTranslation: 'Those Sent Forth', revelationType: 'Meccan', numberOfAyahs: 50, startPage: 581, endPage: 583),
    Surah(number: 78, name: 'An-Naba', nameArabic: 'النبأ', englishName: 'The Tidings', englishNameTranslation: 'The Great News', revelationType: 'Meccan', numberOfAyahs: 40, startPage: 583, endPage: 584),
    Surah(number: 79, name: 'An-Nazi\'at', nameArabic: 'النازعات', englishName: 'Those who drag forth', englishNameTranslation: 'Those Who Pull Out', revelationType: 'Meccan', numberOfAyahs: 46, startPage: 584, endPage: 586),
    Surah(number: 80, name: '\'Abasa', nameArabic: 'عبس', englishName: 'He Frowned', englishNameTranslation: 'He Frowned', revelationType: 'Meccan', numberOfAyahs: 42, startPage: 585, endPage: 586),
    Surah(number: 81, name: 'At-Takwir', nameArabic: 'التكوير', englishName: 'The Overthrowing', englishNameTranslation: 'The Folding Up', revelationType: 'Meccan', numberOfAyahs: 29, startPage: 586, endPage: 587),
    Surah(number: 82, name: 'Al-Infitar', nameArabic: 'الإنفطار', englishName: 'The Cleaving', englishNameTranslation: 'The Cleaving Asunder', revelationType: 'Meccan', numberOfAyahs: 19, startPage: 587, endPage: 587),
    Surah(number: 83, name: 'Al-Mutaffifin', nameArabic: 'المطففين', englishName: 'The Defrauding', englishNameTranslation: 'Those Who Give Short Measure', revelationType: 'Meccan', numberOfAyahs: 36, startPage: 587, endPage: 590),
    Surah(number: 84, name: 'Al-Inshiqaq', nameArabic: 'الإنشقاق', englishName: 'The Sundering', englishNameTranslation: 'The Splitting Asunder', revelationType: 'Meccan', numberOfAyahs: 25, startPage: 589, endPage: 590),
    Surah(number: 85, name: 'Al-Buruj', nameArabic: 'البروج', englishName: 'The Mansions of the Stars', englishNameTranslation: 'The Stars', revelationType: 'Meccan', numberOfAyahs: 22, startPage: 590, endPage: 590),
    Surah(number: 86, name: 'At-Tariq', nameArabic: 'الطارق', englishName: 'The Morning Star', englishNameTranslation: 'The Night-Comer', revelationType: 'Meccan', numberOfAyahs: 17, startPage: 591, endPage: 591),
    Surah(number: 87, name: 'Al-A\'la', nameArabic: 'الأعلى', englishName: 'The Most High', englishNameTranslation: 'The Most High', revelationType: 'Meccan', numberOfAyahs: 19, startPage: 591, endPage: 592),
    Surah(number: 88, name: 'Al-Ghashiyah', nameArabic: 'الغاشية', englishName: 'The Overwhelming', englishNameTranslation: 'The Overwhelming Event', revelationType: 'Meccan', numberOfAyahs: 26, startPage: 592, endPage: 592),
    Surah(number: 89, name: 'Al-Fajr', nameArabic: 'الفجر', englishName: 'The Dawn', englishNameTranslation: 'The Break of Day', revelationType: 'Meccan', numberOfAyahs: 30, startPage: 593, endPage: 594),
    Surah(number: 90, name: 'Al-Balad', nameArabic: 'البلد', englishName: 'The City', englishNameTranslation: 'The City', revelationType: 'Meccan', numberOfAyahs: 20, startPage: 594, endPage: 595),
    Surah(number: 91, name: 'Ash-Shams', nameArabic: 'الشمس', englishName: 'The Sun', englishNameTranslation: 'The Sun', revelationType: 'Meccan', numberOfAyahs: 15, startPage: 595, endPage: 595),
    Surah(number: 92, name: 'Al-Layl', nameArabic: 'الليل', englishName: 'The Night', englishNameTranslation: 'The Night', revelationType: 'Meccan', numberOfAyahs: 21, startPage: 595, endPage: 596),
    Surah(number: 93, name: 'Ad-Dhuha', nameArabic: 'الضحى', englishName: 'The Morning Hours', englishNameTranslation: 'The Glorious Morning Light', revelationType: 'Meccan', numberOfAyahs: 11, startPage: 596, endPage: 596),
    Surah(number: 94, name: 'Ash-Sharh', nameArabic: 'الشرح', englishName: 'The Relief', englishNameTranslation: 'The Expansion of Breast', revelationType: 'Meccan', numberOfAyahs: 8, startPage: 596, endPage: 596),
    Surah(number: 95, name: 'At-Tin', nameArabic: 'التين', englishName: 'The Fig', englishNameTranslation: 'The Fig', revelationType: 'Meccan', numberOfAyahs: 8, startPage: 597, endPage: 597),
    Surah(number: 96, name: 'Al-\'Alaq', nameArabic: 'العلق', englishName: 'The Clot', englishNameTranslation: 'The Clinging Clot', revelationType: 'Meccan', numberOfAyahs: 19, startPage: 597, endPage: 597),
    Surah(number: 97, name: 'Al-Qadr', nameArabic: 'القدر', englishName: 'The Power', englishNameTranslation: 'The Night of Decree', revelationType: 'Meccan', numberOfAyahs: 5, startPage: 598, endPage: 598),
    Surah(number: 98, name: 'Al-Bayyinah', nameArabic: 'البينة', englishName: 'The Clear Proof', englishNameTranslation: 'The Clear Evidence', revelationType: 'Medinan', numberOfAyahs: 8, startPage: 598, endPage: 599),
    Surah(number: 99, name: 'Az-Zalzalah', nameArabic: 'الزلزلة', englishName: 'The Earthquake', englishNameTranslation: 'The Earthquake', revelationType: 'Medinan', numberOfAyahs: 8, startPage: 599, endPage: 599),
    Surah(number: 100, name: 'Al-\'Adiyat', nameArabic: 'العاديات', englishName: 'The Courser', englishNameTranslation: 'Those That Run', revelationType: 'Meccan', numberOfAyahs: 11, startPage: 599, endPage: 600),
    Surah(number: 101, name: 'Al-Qari\'ah', nameArabic: 'القارعة', englishName: 'The Calamity', englishNameTranslation: 'The Striking Hour', revelationType: 'Meccan', numberOfAyahs: 11, startPage: 600, endPage: 600),
    Surah(number: 102, name: 'At-Takathur', nameArabic: 'التكاثر', englishName: 'The Rivalry in world increase', englishNameTranslation: 'The Piling Up', revelationType: 'Meccan', numberOfAyahs: 8, startPage: 600, endPage: 601),
    Surah(number: 103, name: 'Al-\'Asr', nameArabic: 'العصر', englishName: 'The Declining Day', englishNameTranslation: 'The Time', revelationType: 'Meccan', numberOfAyahs: 3, startPage: 601, endPage: 601),
    Surah(number: 104, name: 'Al-Humazah', nameArabic: 'الهمزة', englishName: 'The Traducer', englishNameTranslation: 'The Slanderer', revelationType: 'Meccan', numberOfAyahs: 9, startPage: 601, endPage: 601),
    Surah(number: 105, name: 'Al-Fil', nameArabic: 'الفيل', englishName: 'The Elephant', englishNameTranslation: 'The Elephant', revelationType: 'Meccan', numberOfAyahs: 5, startPage: 602, endPage: 602),
    Surah(number: 106, name: 'Quraysh', nameArabic: 'قريش', englishName: 'Quraysh', englishNameTranslation: 'The Quraish', revelationType: 'Meccan', numberOfAyahs: 4, startPage: 602, endPage: 602),
    Surah(number: 107, name: 'Al-Ma\'un', nameArabic: 'الماعون', englishName: 'The Small kindnesses', englishNameTranslation: 'The Small Kindnesses', revelationType: 'Meccan', numberOfAyahs: 7, startPage: 602, endPage: 603),
    Surah(number: 108, name: 'Al-Kawthar', nameArabic: 'الكوثر', englishName: 'The Abundance', englishNameTranslation: 'Abundance', revelationType: 'Meccan', numberOfAyahs: 3, startPage: 603, endPage: 603),
    Surah(number: 109, name: 'Al-Kafirun', nameArabic: 'الكافرون', englishName: 'The Disbelievers', englishNameTranslation: 'Those Who Deny the Truth', revelationType: 'Meccan', numberOfAyahs: 6, startPage: 603, endPage: 604),
    Surah(number: 110, name: 'An-Nasr', nameArabic: 'النصر', englishName: 'The Divine Support', englishNameTranslation: 'The Help', revelationType: 'Medinan', numberOfAyahs: 3, startPage: 604, endPage: 604),
    Surah(number: 111, name: 'Al-Masad', nameArabic: 'المسد', englishName: 'The Palm Fibre', englishNameTranslation: 'The Palm Fiber', revelationType: 'Meccan', numberOfAyahs: 5, startPage: 604, endPage: 605),
    Surah(number: 112, name: 'Al-Ikhlas', nameArabic: 'الإخلاص', englishName: 'The Sincerity', englishNameTranslation: 'The Purity of Faith', revelationType: 'Meccan', numberOfAyahs: 4, startPage: 605, endPage: 605),
    Surah(number: 113, name: 'Al-Falaq', nameArabic: 'الفلق', englishName: 'The Daybreak', englishNameTranslation: 'The Daybreak', revelationType: 'Meccan', numberOfAyahs: 5, startPage: 605, endPage: 606),
    Surah(number: 114, name: 'An-Nas', nameArabic: 'الناس', englishName: 'Mankind', englishNameTranslation: 'Mankind', revelationType: 'Meccan', numberOfAyahs: 6, startPage: 606, endPage: 606),
  ];
}